### ISSUE TITLE
Slideshow

### ISSUE THREAD

**Issue by sopkomir** [sitecake/sitecake#19]
I do not see the slideshow in sitecake-editor. Is it okay?

**Comment by 2braincells2go** [comment]
I miss the ability to use default slideshow in SiteCake 2. Even see the slideshow in demo portfolio but no way to edit:(

Since the toolbar can be configured to show slideshow option, why not leave it in V2 and those that do not want to use, do not have to.

I miss the feature so much...

**Comment by nikolamircic** [comment]
We decided to leave slideshow with the Sitecake by default. Still we are not sure which open source slideshow to use. Right now, if you drag and drop more than one image, Sitecake will create image collage. That is what v2 has at the moment.
