### ISSUE TITLE
changes in the admin mode not updating

### ISSUE THREAD

**Issue by bitonchen** [sitecake/sitecake#35]
Every change i publish in the admin mode isnt update.
i add image or changing text and click publish... then click refresh and nothing changed

**Comment by sitecake** [comment]
Sitecake 2.0.3 has already built in page manager in. It can clone, delete and reorder HTML pages. But UI is not finished so it's disabled. Page manager sets certain ID for each page, and it's in the header of each HTML, as js var:

<script type="text/javascript">var scpageid="5a83bae116daa8b7299b17fdf189489e49ade1e2";</script>

Once it clones the pages it changes the scpageid. What you did, I suppose, is that you manually cloned (copied) pages and all your pages have same id. So page manager saves content to the first page with the id he has, this might make a problem when saving the content.

Now here is the solution, once you manually clone html page, delete this part from the header

<script type="text/javascript">var scpageid="5a83bae116daa8b7299b17fdf189489e49ade1e2";</script>

and Sitecake will create new id for the page. That's it. Relase 2.1 will fixed this issue. We will publish it this week.

**Comment by bitonchen** [comment]
WOW.... you are just amazing!! quick and informative responses

**Comment by nullart** [comment]
please advise how we can clone a page manually.
