### ISSUE TITLE
SiteCake toolbar dissappearing on non-index.html files.

### ISSUE THREAD

**Issue by brechtryckaert** [sitecake/sitecake#36]
I presume I found a bug. 
'm working on a site for a client that is using SiteCake V2.0.3. 
I'm able to load the toolbar on the homepage by going to url/sc-admin.php. However, if I click any of my links to another page, the toolbar vanishes. As far as I found in the documentation, version 2 does no longer need the php include to be added to every single page for the toolbar to work.
Strange thing is: to create the other pages, I've simply copied over the index.html's code and started changing the contents, but I started from the page that is working with Sitecake. 

Is this something known? 
=> http://wijnhuis1.mediagraaf.be

**Comment by sitecake** [comment]
Yes it's a bug. Read more about this issue here.
https://github.com/sitecake/sitecake/issues/35

**Comment by brechtryckaert** [comment]
Thanks for the swift reply. Deleted the scpageid references, but the same behaviour remains.

**Comment by sitecake** [comment]
Try adding sc-nav class to your main menu ul

<ul class="sc-nav">
...
</ul>

on all other links that you want to invoke toolbar when open a new page you need to add
sc-admin.php?page= into the link, like this

http://wijnhuis1.mediagraaf.be/sc-admin.php?page=degustaties.html

**Comment by brechtryckaert** [comment]
Awesome. That fixed it. Thank you so much for your very rapid response!
