### ISSUE TITLE
How to access pages in the editor when not in the main navigation

### ISSUE THREAD

**Issue by richardwo** [sitecake/sitecake#37]
Hi,
I can see from the sample that you can use class sc-nav in the main navigation to access other pages in the editor.
How can you access other pages if they are not in the navigation bar. For example I have a footer with a link to terms and conditions.
Thanks.

**Comment by nivancevic** [comment]
In version 2.0.x there's to have automatically adjusted links outside of the sc-nav block. In 2.1 all links on a page (regardless of sc-nav) will be adjusted.
One workaround would be to specify the page directly in the request URL query parameters. For example:
http://yourdomain.com/sc-admin.php?page=terms.html
