### ISSUE TITLE
PHP Strict Standards Error

### ISSUE THREAD

**Issue by 2braincells2go** [sitecake/sitecake#45]
Hi. After getting "zend started output errors" trying version 1.0.41, found version 2 here.

Got V2.2.1 working, but producing error log with:

PHP Strict Standards:  Static function Sitecake\Services\Service::name() should not be abstract in /home/xxxxxxx/public_html/sitecake/2.2.1/server/Sitecake/Services/Service.php on line 9

Running PHP Version 5.4.38

Any ideas how to fix this?

Really wish I could run v1.0.41 but the zend errors stopped me dead in tracks...

Many thanks in advance!

**Comment by nikolamircic** [comment]
Have you built the v2.2.1 from the source?

**Comment by 2braincells2go** [comment]
I downloaded from the link below, so not no did not build from source:

https://github.com/sitecake/sitecake/wiki/Getting-Started

BTW: can no longer download from http://sitecake.com/download/, get 403 forbidden error

**Comment by nikolamircic** [comment]
Ok. I updated version available to v2.2.5 it should solve your issues (and some more). 
So go to Getting Started wiki page, download v2.2.5 and let us know if it works.

**Comment by 2braincells2go** [comment]
Thank you! Will give 2.2.5 a try and report back to you.

**Comment by 2braincells2go** [comment]
Quick question: Other versions have sc-admin.php but 2.2.5 has sitecake.php. Is there a reason for this or as I am assuming it really does not matter?

**Comment by nikolamircic** [comment]
sitecake.php is new entry point to Sitecake editor. It's simpler to remember.

**Comment by 2braincells2go** [comment]
Thank you Nikola, I assumed that the naming of sc-admin.php was mute point but "assuming" normally gets me in trouble:)

I tried 2.2.5 and solved my issue. Appreciate the fast response.

One last question that really does not belong here, but will point me in right direction: Concerning V1.0.41 - getting zend error. Should I open a trouble ticket at your site or do you have troubleshoot guide/forum I look at first?

Many, many thanks.

**Comment by nikolamircic** [comment]
Regarding 1.0.41 issue, ... open a ticket on the website. Even better, switch to v2, if you have time.

**Comment by 2braincells2go** [comment]
Thank you!
