### ISSUE TITLE
Non-functional demo

### ISSUE THREAD

**Issue by sebie** [sitecake/sitecake#47]
Self-explanetory really, as the title suggests.

The link to the demo [(sitecake.com/demo)](http://sitecake.com) redirects to [http://sitecake.com/demo/live/557eb45194924/sitecake.php](http://sitecake.com/demo/live/557eb45194924/sitecake.php) which is a blank page.

Feel free to ask questions relationig to the issue below.

**Comment by nikolamircic** [comment]
Sorry guys. What happened is that we are overwhelmed with visits from ProductHunt and HackerNews. Our demo is unable to cope with so much uploaded content and hard disk fills within 30 minutes. Then it breaks. :( 

We are working on it....

**Comment by sebie** [comment]
Oh it's fine. Just didn't know what happend. I could still ping server -- I assumed it was still alive.

HN strickes again.
