### ISSUE TITLE
Upgrade to a new version?

### ISSUE THREAD

**Issue by La-Geek** [sitecake/sitecake#48]
Hi,
sitecake looks great. But I am wondering how to update this CMS?
Is this doc still up to date?
http://sitecake.com/docs/how-to-upgrade-sitecake.php

How we will become aware of updates?

Thanks in advance!

**Comment by nikolamircic** [comment]
At this moment there is no auto migration script from v1 -> v2. What you can do is to manually open each v1 page in browser and save as HTML. Once you did it for all pages just add new v2 in the same folder with HTML files and you are good to go.

**Comment by La-Geek** [comment]
Hi, thanks for you fast reply.
I wanted to ask, how to manage updates in future?
And how I will know, when new updates are available?

**Comment by nikolamircic** [comment]
Sitecake has built in auto update feature. It's still not activated, since we are testing it, but we plan to release it with some of forthcoming releases.

**Comment by La-Geek** [comment]
Sounds great! Do you need help with localisation (german)? Or testing?

**Comment by nikolamircic** [comment]
Thanks! 

We have Sitecake in German. http://sitecake.com/docs/how-to-change-sitecake-ui-language.php
This works for v2 also. 

Testing, yes of course. You are more than welcome. We will ping you with new release.
