### ISSUE TITLE
How to use additional template folder?

### ISSUE THREAD

**Issue by ZhiguoZhang** [sitecake/sitecake#49]
hi, i am tring to use a sub-folder which name template under sitecake folder( root) , like this:

* root folder
    * --sitecake
    * --template
           * --portfolio
                 
               
          * --index.html

but how to config this, looks like the default folder is alway sitecake root folder and not like template wiki write, there could be template root folder. 

thank you!

best regards

**Comment by nikolamircic** [comment]
You have to put Sitecake folder next to your HTML files. That's it
