### ISSUE TITLE
Including the wrong config file.

### ISSUE THREAD

**Issue by PidaPan** [sitecake/sitecake#50]
There is an issue with the `include` statement in line [#L35](https://github.com/sitecake/sitecake/blob/master/src/admin-full.php#L35) of [admin-full.php](https://github.com/sitecake/sitecake/blob/master/src/admin-full.php). Depending on the global php `include_path` config the wrong config file could be loaded ending in an exception when the settings will be used.

In this case the `include` will look within the `include_path` first. If there exists a `config.php` this one will be included instead of the sitecakes config file. The file name is very common so it is not unlikely that there is a different one.

I would suggest to use an absolute path within the `include` statement:
```php
include(dirname(__FILE__) . '/config.php');
```

**Comment by philkaroo** [comment]
The following does work:
`include('sitecake/2.2.8/server/config.php');`

**Comment by sitecake** [comment]
Thanks for the suggestion. You are correct, that was the problem. Fixed in the version 2.2.9.
