### ISSUE TITLE
Files won't upload.

### ISSUE THREAD

**Issue by HamLettuceTomato** [sitecake/sitecake#60]
Attempted to add .txt, .pdf, .doc files through the admin interface both by drag and drop and the upload files method. Neither worked. Files weren't uploaded to the server, and all URLs point to 'site/true'.
Am I missing something or is this an issue?

**Comment by osdebianly** [comment]
I have the same problem
1,  find sitecake/2.2.9/server/vendor/league/flysystem/src/Filesystem.php  at  99 change to 
return  $this->getAdapter()->writeStream($path, $resource, $config);
 2, sitecake/2.2.9/server/Sitecake/Services/Upload/UploadService.php  at 45 line ,change to 
return $this->json($request, array('status' => 0, 'url' => $res['path']), 200); 

good luck!
