### ISSUE TITLE
Idea: columns

### ISSUE THREAD

**Issue by eduardoarandah** [sitecake/sitecake#61]
Having one button to divide a sc-content in 2,3,4

It would remove sc-content class from parent, and create a row->column with sc-content on each one

bootstrap would have to be mandatory, I guess...

What do you think? is it out of project goals?

![asdf](https://cloud.githubusercontent.com/assets/4065733/8624719/b3e49fd8-26ff-11e5-8eed-5cec447fc2a3.jpg)

**Comment by nikolamircic** [comment]
Idea is good. Just that we can't be tied only to one framework, Bootstrap. Sitecake should work with or without Bootstrap. 

Thanks for your request, we will consider how we can implement it.
