### ISSUE TITLE
Add floating for images

### ISSUE THREAD

**Issue by JPustkuchen** [sitecake/sitecake#64]
Hi and thanks a lot for your great great work! :)

Today I have a little question that is quite important for several use cases: Is there a built in possibility to float inline images without a static container?

We know many users that would like to use it. Adding a custom class to the image for example would be a possibility.

**Comment by sitecake** [comment]
You can add custom class to the image. Here is how
https://github.com/sitecake/sitecake/wiki/User-Styles
