### ISSUE TITLE
Making columns?

### ISSUE THREAD

**Issue by khromov** [sitecake/sitecake#65]
Read docs, tested demo, but still can't figure out how to create for example a 2 or 3 column layout. It seems to be if you added the column by hand before running Sitecake, you can place content in columns. But you can't create columns from inside Sitecake? That is a big omission and should be fixed.

**Comment by nikolamircic** [comment]
Templates / websites are designed by designers. Designers do colors, fonts, styles and layout. Website owner takes care after content, he is editing a website with text and images by using existing pre-designed styles and layouts. Columns are part of the layout and thus should be prepared in HTML by the designer.

Sitecake has been developed as a CMS for editing existing websites, for quick changes over the existing content. We have planned custom HTML snippets that can be prepared by template designer and pulled down from the toolbar. (eg. multiple column layouts). It will be put on feature voting by users to determine the priority among other features.

**Comment by khromov** [comment]
The snippet thing sounds like a good idea, looking forward to it.
