### ISSUE TITLE
Add body classes when logged in

### ISSUE THREAD

**Issue by szyam** [sitecake/sitecake#69]
More of an enhancement  but I'd love to a body class when logged in, other that random stuff like "GN3KFNTBD". Or even on the containers themselves. Awesome stuff, please keep it up!

**Comment by sitecake** [comment]
Thanks for the support!
Could you please provide more information on this? For example, what would be the use case for having human readable Sitecake class names on DOM elements?

Thanks

**Comment by szyam** [comment]
Thanks for the reply. 

I was working on a project for a client, a small one page menu. To make it easier for him to update, I wanted to add a :before pseudo element to some of the editable elements, to show a small name for them. So an H2 for example, would show a small gray "H2" positioned absolutely to the left of the element. I was looking for a hook to use when logged in.

**Comment by nikolamircic** [comment]
There is a js variable that can tell you if you are in Sitecake edit mode or not. You can use it and apply custom CSS for edit mode only. With this CSS you can, for example, give different HTML tags different backgrounds or labels.

**Comment by szyam** [comment]
Thank you, I'll try that
